### ISSUE TITLE
add "delete record" UX 

### ISSUE THREAD

**Issue by kellyhiser** [therabble/ca.epl.capitalcityrecords#233]
ideally, I think this would allow admin to delete records anywhere in the publishing chain. specifically for the next round of CCR submissions, Alex needs previous submissions cleared out of Jury.

**Comment by kellyhiser** [comment]
addressed: https://github.com/therabble/musicat-stem/issues/28

**Comment by whblondeau** [comment]
Requirements/task breakout for letting qualified admins delete records:
- [ ] list all records available for admin's context (namespace) (absolutely DO NOT expose deletion options cross-collection)
- [ ] display records according to context (e.g. submission round)
- [ ] provide link for record deletion
- [ ] create an undelete mechanism, because people will fuck up and panic.

Note that this might be rolled into the existing interface, but I'm thinking that keeping this a separate interface is more straightforward and less subject to confusion.
