### ISSUE TITLE
Need a link to invite EMA Winners to upload their albums

### ISSUE THREAD

**Issue by raqmann** [therabble/ca.epl.capitalcityrecords#251]
Hello team,

I am planning on sending email invites to the Edmonton Music Award Winners to join CCR as early as possible next week. I will need to provide them a link to upload their album, album art and artist image, their artist and album info, and be able to sign the license.

As this is not an open round, where they can submit their album on the site, would there be a workaround for this process? 

I see one related issue #247 was created last month.

Thank you!

**Comment by prestonaustin** [comment]
Our work in progress for CCR includes a button to create a "New Invitation"
added to the invite page, which let's you start a new album at that stage
without needing a submission to exist. It will require at minimum an
artist's name, album name, and email address to which the invite get's
sent. After that the artist has an experience identical to that of a normal
submission, but will have a bit less information pre-filled when they get
to the complete submissions interface, and no tracks already loaded
(currently we have to include a placeholder track for technical reasons to
have a record that meets the expectations of the existing interface, that
may or may not still be the case when we deploy this, I just haven't had a
chance to change the downstream code not to need it.)

That should entirely meet this need, correct?

That is planned to be part of Tuesday's updates. We have an unresolved
issue that prevents using the same email for more than one album
submission, and a related but that is posing problems for creating new
albums for an artist with an existing album, I hope to fix both of these
before Tuesday as well but I don't think they block you and both can be
worked around if we need to. Let's confirm this along with the other
request via email on Monday afternoon, and get timing narrowed down for you
as to when things are being changed, as well as planned times for new
feature review and questions/feedback if you need edits and updates.

**Comment by raqmann** [comment]
Thank you @prestonaustin.
One question, we won't know the exact album the artist will choose to highlight on Capital City Records until they respond to the invite. Would it be possible to have a placeholder for the Album name as well that we can change when they submit the tracks, artwork and the rest of their information? 

Thanks!
Raquel

**Comment by prestonaustin** [comment]
That may be tricky as right now the slug is a persistent identifier and
contains the album and artist name from the submission. We did this
originally to keep foreign incoming URLs (like those from MARC exports)
both human readable and reliable, and make it easy for others' code to
heuristically construct paths to MUSICat resources from lists of albums in
non-MUSICat datasets.

Right now Album and Artist titles in the metadata and displayed on the site
can change, but the URL then wouldn't match. It would function but feels
untidy.

We're already looking at changing this because it makes fixing certain
errors difficult and also Nashville had a similar case, but it's not a
trivial change and it's not entirely clear after what point the slug should
be frozen permanently. I want to implement a way to serve permanent
redirects at the old URL to the new one when slugs are changed so inbound
pointers tend to keep working. It's a bit of extra work but seems worth it.

As a workaround here, I'm tempted to invite them to a preliminary form that
we use to gather the data to power accurate invitations, but I'll look at
it with fresh eyes in the morning and see if I can't find a way to leave
the slug mutable or unset prior to the artist entering metadata at the
complete-submission stage.

**Comment by raqmann** [comment]
Hi Preston,

How about this as a workaround. I can send the artists a congratulations email (not through Musicat) informing them of their guaranteed spot on CCR that asks them to respond with the Album title they choose to share and confirm their artist/band name.

In that email, I will let them know they will shortly receive the Invite Email (through the Musicat admin) which will provide information around the next steps to complete their submission process. This email will be the one I add through the GitHub pull request and can include a space for the Artist and Album name (I did just add a new file there, but will take it out, modify it and re-add it).

Let me know if that works :) 
Best,
Raquel

**Comment by kellyhiser** [comment]
Let's go with Raquel's proposed workaround. The slug issue is something I want to get fixed in a comprehensive and smart way, not in a last-second, just make it work way.

**Comment by prestonaustin** [comment]
OK, I'm on it that way and will use the new email template, so that is a
straightforward approach for tomorrow. We'll circle back on The Naming Of
Slugs matter later.
