### ISSUE TITLE
MARC integration

### ISSUE THREAD

**Issue by lahollen** [therabble/ca.epl.capitalcityrecords#30]
a. could we link to art in  the 856 field
b. Rabble will populate that field with a URL for largish art

**Comment by lahollen** [comment]
@jjg can you search for your last email correspondence with Shana (?) at EPL in cataloging to see if we're currently blocked by EPL on this issue?

**Comment by jjg** [comment]
Here's the latest info I have on this.  I emailed a sample MARC record to Shona that was generated with this script:

     https://github.com/therabble/musicat-api/blob/master/experimental/marcgen.js

Here's the notes from Shona's review of the file:

Hi Jason,
 
Suggested edits to the first sample record can be seen below in red text. The 505 subfield g playing time is an optional element, and so could be omitted if not available. A helpful reference for MARC coding of bibliographic data may be found at http://www.loc.gov/marc/bibliographic/.
 
=LDR  00357njm  22000971  4500 – j = Musical sound recording http://www.loc.gov/marc/bibliographic/bdleader.html
=006  m\\\\\o\\h\\\\\\\\ -- http://www.loc.gov/marc/bibliographic/bd006.html
=007  sz\zuunnnnuned -- http://www.loc.gov/marc/bibliographic/bd007.html
=007  cr\nna||||||||
=100  0\$amark-davis
=245  10$aEliminate the Toxins$h[electronic resource] /$cmark-davis. – http://www.loc.gov/marc/bibliographic/bd245.html
=246  1\$aEliminate the Toxins$helectronic resource   -- The 246 field is only necessary where an alternate form of the title requires an access point http://www.loc.gov/marc/bibliographic/bd246.html
=260  \\$bSaved by Radio/Saved by Vinyl,$cnull -- http://www.loc.gov/marc/bibliographic/bd260.html
=300  \\$aonline resource (streaming audio) :$bdigital
=505  00$tEliminate the Toxins$gnull$tGo To Ground$gnull$tWounded Wing$gnull
 
The records should also include some kind of unique alpha-numeric identifier, typically included in the 001 or 035 subfield a.
 
Let me know if you have any questions re: the above.

I also took a screenshot since the response was color-coded and Github seems to have swallowed some of the text above:

![feedback2](https://cloud.githubusercontent.com/assets/122858/8748471/5147c6d2-2c60-11e5-93a8-8990885a595f.png)

I think the next step is to review these edits and modify the script to generate an updated file for review.  Once that passes muster, the code in the test script can be incorporated elsewhere (perhaps an API endpoint or client-side) to generate these on-demand.

Let me know if you have any questions or need any additional details from me, but for now I'm assigning back to @lahollen for review.

**Comment by lahollen** [comment]
@prestonaustin can you review please and let me know if further actions should be taken or I should reassign to someone

**Comment by prestonaustin** [comment]
This can be assigned as is imo. Doing this on the client side might be an
ideal starter task for JD. It's an isolated chunk of output that can be
built from existing endpoints. Basically, we could add a view as MARC path
to the public app, make these edits to the output, and also include links
to a largish album graphic per @acecarruthers more recent request.

**Comment by lahollen** [comment]
@jdlien I'm assigning this ticket to you! See convo above and follow up with any questions you have by tagging with the @.

**Comment by acecarruthers** [comment]
Just touched base with Shona about this. Here is some pertinent information that she shared with me:
- after you are both satisfied that the test record is formatted correctly we'll need to do a test load of some records into BiblioCommons 
- sometimes formatting in BiblioCommons is touchy so it may have to be run a few times
- there can be a lag in how often BiblioCommons refreshes their catalogue, so it may be hours before EPL can review a test load
- to include album art the 856 field must link to a thumbnail image of the album cover. It shouldn't be more than a couple hundred pixels.

**Comment by acecarruthers** [comment]
The max width for the album art thumbnails is 135px

**Comment by prestonaustin** [comment]
We'll then populate the appropriate MARC value with URLs that return
exactly 135px assets, to offer the best quality result that fits this
constraint.

**Comment by prestonaustin** [comment]
Delayed by API entanglements, scheduled for completion together with @jjg and @nagapampa on Tuesday

**Comment by kellyhiser** [comment]
MARC export exists as dev tool, we can provide records whenever.
